src/features/planning/components/tools/PlanVisitationFrequency.vue, src/views/PlanView.vue
=> Implement `Visitation Frequency` tool for plans

src/features/game_data/useBuildingData.ts, src/features/game_data/useExchangeData.ts, src/features/game_data/useMaterialData.ts, src/features/game_data/usePlanetData.ts, src/stores/gameDataStore.ts, src/stores/planningStore.ts, src/tests/util/data.test.ts, src/util/data.ts
=> Add `inertClone` to loose reactivity on store data or any refs

src/features/planning/usePlanCalculation.ts, src/features/planning/usePlanCalculation.types.d.ts, src/views/PlanView.vue
=> Allow Plan Material I/O to split between production and workforce

src/features/game_data/useBuildingData.ts, src/features/planning/usePlanCalculation.ts, src/features/planning/usePlanCalculationHandlers.ts, src/features/planning_data/planData.api.ts, src/features/planning_data/planningData.schemas.ts, src/features/planning_data/usePlan.ts, src/features/planning_data/usePlan.types.d.ts, src/lib/apiService.ts, src/tests/features/planning/usePlanCalculation.test.ts, src/tests/features/planning/usePlanCalculationHandlers.test.ts, src/tests/features/planning_data/planData.api.test.ts, src/tests/features/planning_data/usePlan.test.ts, src/tests/lib/apiService.test.ts, src/tests/util/data.test.ts, src/util/data.ts, src/views/PlanView.vue
Also includes NavigationGuard when trying to leave and having unsaved changes.
close #33
=> Implement Planning Create, Save and Reload

src/features/account/account.schemas.ts
Thanks to `Dubbe` from PCT Discord for pointing this out.
fix #35
=> Reduce token schema length 

src/features/game_data/useBuildingData.ts, src/features/planning/usePlanCalculation.ts, src/features/planning/usePlanCalculationHandlers.ts, src/views/PlanView.vue
=> Improve plan header, exclude infrastructure building options

index.html, package.json, pnpm-lock.yaml, src/App.vue, src/features/navigation/components/NavigationBar.vue, src/main.ts, src/views/EmpireView.vue, src/views/PlanView.vue
=> Introduce `unhead`, set page titles

src/features/planning/calculations/bonusCalculations.ts, src/tests/features/planning/calculations/bonusCalculations.test.ts
=> FIX: Fertility calculation

src/features/planning/components/PlanProductionBuilding.vue, src/features/planning/components/tools/PlanRepairAnalysis.vue, src/features/planning/components/tools/planRepairAnalysis.types.ts, src/features/planning/usePlanCalculation.ts, src/features/planning/usePlanCalculation.types.d.ts, src/layout/highcartsOptions.ts, src/views/PlanView.vue
=> Implements Plan Repair Analysis Tool

src/features/wrapper/components/EmpireDataWrapper.vue, src/stores/gameDataStore.ts, src/stores/planningStore.ts, src/stores/userStore.ts, src/tests/stores/planningStore.test.ts
=> Handle 404 on plan loading & fully reset stores on logout

.github/workflows/build.yml, .github/workflows/coverage.yml, .github/workflows/lint.yml, .github/workflows/test.yml
=> Restructure GitHub workflows

src/features/wrapper/components/ManageDataWrapper.vue, src/views/ProfileView.vue
=> Specify loads in `ManageDataWrapper`

src/assets/help/fio_burn.md, src/features/empire/components/EmpirePlanList.vue, src/features/fio/components/FIOBurnPlanTable.vue, src/features/fio/components/FIOBurnTable.vue, src/features/fio/useFIOBurn.ts, src/features/fio/useFIOBurn.types.ts, src/features/navigation/components/NavigationBar.vue, src/features/preferences/usePreferences.ts, src/features/preferences/userDefaults.ts, src/features/preferences/userPreferences.types.ts, src/features/profile/components/UserPreferences.vue, src/features/sharing/components/SharingButton.vue, src/features/xit/components/XITActionButton.vue, src/features/xit/useXITAction.ts, src/features/xit/xitAction.types.ts, src/features/xit/xitConstants.ts, src/layout/prunplannerNaiveUI.ts, src/router/index.ts, src/tests/features/fio/useFIOBurn.test.ts, src/tests/features/preferences/usePreferences.test.ts, src/tests/features/xit/useXITAction.test.ts, src/tests/features/xit/xitConstants.test.ts, src/tests/util/axiosSetup.Header.test.ts, src/tests/util/data.test.ts, src/util/data.ts, src/views/fio/FIOBurnView.vue
=> Implements FIO Burn View and XIT Resupply Action

src/features/fio/components/FIOBurnTable.vue, src/features/xit/components/XITBurnActionButton.vue, src/features/xit/useBurnXITAction.ts, src/features/xit/useXITAction.ts, src/features/xit/xitAction.types.ts, src/tests/features/xit/useXITAction.test.ts, src/tests/features/xit/useXITBurnAction.test.ts
Move generation of XIT JSON into own composable and separate from burn drawer.
=> refactor(xit): separate action from burn

src/features/navigation/components/NavigationBar.vue
Generates menu sections as computed value in order to watch userStores hasFIO computed on delayed user profile information.
fix #81
=> fix(navigation): user hasFIO navigation parts

src/assets/css/style.css, src/features/empire/components/EmpirePlanList.vue, src/layout/prunplannerNaiveUI.ts
=> style: increase font-sizes to 16/14px

package.json, src/assets/css/style.css, src/features/market_exploration/useMarketExplorationChart.ts, src/features/navigation/components/NavigationBar.vue, src/main.ts, src/router/index.ts, src/tests/features/market_exploration/useMarketExplorationChart.test.ts, src/tests/router/router.test.ts, src/views/NoneView.vue, src/views/market-data/MarketExplorationView.vue
=> feat(marketexploration): implement exploration charts

src/App.vue, src/AppProvider.vue, src/layout/prunplannerNaiveUI.ts, src/main.ts
Separates all providers into AppProvider.vue which itself then contains the actual App.vue to be initialized. Adds naive-ui loading bars.
=> feat(layout): app provider & loading bar

src/App.vue, src/features/account/components/LoginComponent.vue, src/router/index.ts, src/views/ImprintToSView.vue
=> feat(imprint-tos): add imprint and tos

src/features/market_exploration/useMarketExplorationChart.ts, src/tests/features/market_exploration/useMarketExplorationChart.test.ts
=> feat(marketexploration): skip same trade volumes

src/features/api/optimize.api.ts, src/features/api/schemas/optimize.schemas.ts, src/features/cx/usePrice.ts, src/features/cx/usePrice.types.ts, src/features/planning/components/tools/PlanOptimizeHabitation.vue, src/lib/query_cache/queryRepository.ts, src/lib/query_cache/queryRepository.types.ts, src/tests/features/api/optimize.api.test.ts, src/tests/features/cx/usePrice.test.ts, src/tests/test_data/api_data_optimize_habitation.json, src/views/PlanView.vue
implements the habitation optimization tool on plans, adding backend api call with schema validation, expands tests
close #26
=> feat(plan): implement habitation optimization

src/features/market_exploration/useMarketExplorationChart.ts, src/tests/features/market_exploration/useMarketExplorationChart.test.ts, src/views/market-data/MarketExplorationView.vue
Sanitizes data spikes properly
=> fix(marketexploration): sanitize data spikes

src/features/fio/useFIOStorage.ts, src/features/planning/components/tools/PlanSupplyCart.vue, src/features/xit/components/XITTransferActionButton.vue, src/tests/features/fio/useFIOStorage.test.ts, src/tests/test_data/api_data_fio_storage.json, src/views/PlanView.vue
Introduces the Supply Cart tool to PlanView, allowing users to view and manage supply needs based on FIO storage data. Adds the useFIOStorage composable for storage option handling, integrates XIT transfer actions, and provides comprehensive tests for storage logic. Updates PlanView to support the new tool and enables the Supply Cart button.
close #24
=> Add Supply Cart feature with FIO storage integration

src/features/material_tile/components/MaterialTile.vue, src/main.ts
fixes an issue where adding a recipe lags due to gamedata wrapper retriggering on MaterialTile
=> fix(plan): delayed plan

package.json, pnpm-lock.yaml, vite.config.ts
=> chore(vite): upgrade packages, reduce chunks

src/assets/help/changelog.md, src/assets/help/tools_resource_roi_overview.md, src/features/navigation/components/NavigationBar.vue, src/features/resource_roi_overview/components/ResourceROITable.vue, src/features/resource_roi_overview/useResourceROIOverview.ts, src/features/resource_roi_overview/useResourceROIOverview.types.ts, src/router/index.ts, src/tests/features/resource_roi_overview/useResourceROIOverview.test.ts, src/views/HelpView.vue, src/views/tools/ResourceROIOverviewView.vue
Implements the Resource ROI Overview tool, including new components, composables, types, and tests. Adds navigation and routing for the new tool, updates help documentation. The tool allows users to analyze resource extraction ROI across planets with optimal setups and various filters.
close #130
=> feat(resourceoverview): implements resource overview

src/features/exchanges/components/CXPreferenceSelector.vue, src/features/preferences/usePreferences.ts, src/features/preferences/userDefaults.ts, src/features/preferences/userPreferences.types.ts, src/features/profile/components/UserPreferences.vue, src/tests/features/preferences/usePreferences.test.ts, src/views/HelpView.vue, src/views/ProfileView.vue
=> feat(preference): keep user preferred cx uuid

src/assets/help/changelog.md, src/features/planning/usePlanCalculation.ts, src/features/planning/usePlanCalculationHandlers.ts
=> fix(plan): handle plan name on saveability

src/assets/help/changelog.md, src/lib/apiService.ts, src/lib/query_cache/queryRepository.ts, src/stores/planningStore.ts, src/views/ExchangesView.vue
=> fix(exchange): preference update not persisted

src/assets/help/changelog.md, src/features/xit/components/XITTransferActionButton.vue
=> fix(xit): skip 0 value elements in XIT Transfer

netlify.toml, package.json, scripts/write-version.js, src/App.vue, src/assets/help/changelog.md, src/layout/components/VersionUpdateNotification.vue, src/lib/useVersionCheck.ts, src/ui/components/PSelect.vue, src/ui/components/PSelectMultiple.vue, vite.config.ts
Introduces a build script to generate version.json and a composable (useVersionCheck) to poll for new versions in production. Adds a VersionUpdateNotification component that prompts users to reload when an update is available, and integrates it into App.vue. Also updates Netlify config to prevent caching of index.html. Removes version file generation from vite.config.ts in favor of the new script.
=> feat(build): creates a version.json, notifies user

src/assets/help/changelog.md, src/features/account/components/VerifyEmailComponent.vue, src/features/api/schemas/user.schemas.ts, src/features/api/userData.api.ts, src/features/api/userData.types.ts, src/features/profile/components/ChangePassword.vue, src/features/profile/components/ChangeProfile.vue, src/features/profile/components/UserPreferences.vue, src/lib/query_cache/queryRepository.ts, src/lib/query_cache/queryRepository.types.ts, src/lib/usePostHog.ts, src/router/index.ts, src/tests/features/api/userData.api.test.ts, src/tests/lib/query_cache/queryStore.test.ts, src/tests/lib/usePostHog.test.ts, src/ui/components/PCheckbox.vue, src/ui/components/PFormSeperator.vue, src/ui/components/PInput.vue, src/ui/index.ts, src/views/ProfileView.vue, src/views/VerifyEmailView.vue
- Edit Profile (FIO, PrUn Username, Email)
- Trigger Email Verification
- Email verification code screen to validate
- increased test coverage
close #13
=> feat(profile): implements profile

src/assets/help/changelog.md, src/features/planet_search/components/PlanetSearchResults.vue, src/features/resource_roi_overview/useResourceROIOverview.ts, src/features/roi_overview/components/ROIOverviewTable.vue, src/features/roi_overview/useROIOverview.ts, src/layout/components/ComputingProgress.vue, src/ui/components/PProgressBar.vue, src/ui/index.ts, src/views/EmpireView.vue, src/views/fio/FIOBurnView.vue, src/views/tools/ResourceROIOverviewView.vue
Full parallel calculation on empire and fio burn for plans, same overlay visual on progress in roi and resource roi overview.
Also fixes a small issue where material tiles were not properly key'ed on Planet Search.
=> feat(calculations): parallel calculation, visual indication

src/assets/help/changelog.md, src/features/exchanges/components/CXPlanetPreferenceTable.vue, src/features/fio/components/FIOBurnTable.vue, src/features/material_tile/components/MaterialTile.vue, src/features/planning/components/tools/PlanCOGMTable.vue, src/features/planning/components/tools/PlanConstructionCart.vue, src/features/production_chain/components/GraphAnalysisMaterials.vue, src/features/resource_roi_overview/components/ResourceROITableFilters.vue, src/features/xit/components/XITBurnActionButton.vue, src/features/xit/components/XITTransferActionButton.vue, src/views/PlanView.vue, src/views/tools/HQUpgradeCalculatorView.vue
=> improve(materialtile): add missing key properties

knip.ts, src/App.vue, src/assets/css/style.css, src/assets/help/changelog.md, src/database/composables/useIndexedDBStore.ts, src/features/api/schemas/sharingData.schemas.ts, src/features/api/sharingData.api.ts, src/features/api/sharingData.types.ts, src/features/planning_data/usePlan.ts, src/features/wrapper/components/WrapperGameDataLoader.vue, src/features/wrapper/components/WrapperPlanningDataLoader.vue, src/layout/components/AppFooter.vue, src/layout/components/HomepageHeader.vue, src/lib/query_cache/queryRepository.ts, src/lib/query_cache/queryRepository.types.ts, src/router/index.ts, src/router/router.d.ts, src/tests/features/api/sharingData.api.test.ts, src/tests/features/planning_data/usePlan.test.ts, src/views/HomepageView.vue, src/views/PlanLoadView.vue, src/views/PlanView.vue
feat(clone): clone shared plan
improve(layout): non-auth user layouts
=> Clone Shared Plans, Layout adjustments

src/features/planning/components/PlanExperts.vue, src/features/planning/components/PlanInfrastructure.vue, src/features/planning/components/PlanProductionBuilding.vue, src/features/planning/components/PlanProductionRecipe.vue, src/features/planning/components/tools/PlanConstructionCart.vue, src/ui/components/PInputNumber.vue
=> feat(plan): construction cart material based

src/features/planning_data/usePlan.ts, src/tests/features/planning_data/usePlan.test.ts
skip if not a proper cogc because Invalid or on strike fix #261
=> fix(plan): invalid cogc is not initalized from data

src/features/cx/components/MaterialCXOverviewTable.vue, src/features/endpoints/components/APIKeyManagement.vue, src/features/exchanges/components/CXExchangePreference.vue, src/features/exchanges/components/CXTickerPreference.vue, src/features/government/components/PlanetPOPRTable.vue, src/features/material_tile/components/MaterialTile.vue, src/features/planet_search/components/PlanetSearchAdvanced.vue, src/features/planning/components/PlanOverview.vue, src/features/planning/components/PlanWorkforce.vue, src/features/planning/components/tools/PlanCOGMTable.vue, src/features/planning/components/tools/PlanConstructionCart.vue, src/features/planning/components/tools/PlanOptimizeHabitation.vue, src/features/planning/components/tools/PlanVisitationFrequency.vue, src/features/production_chain/components/GraphAnalysisExpertise.vue, src/features/production_chain/components/GraphAnalysisMaterials.vue, src/features/production_chain/components/GraphAnalysisWorkforce.vue, src/features/profile/components/UserPreferences.vue, src/features/repair_analysis/components/DayRepairMaterialTable.vue, src/features/xit/components/XITBurnActionButton.vue, src/features/xit/components/XITTransferActionButton.vue, src/lib/query_cache/QueryCacheView.vue, src/ui/components/PTable.vue, src/ui/index.ts
Remove most instances of NaiveUI ntable in favor of own, smaller ptable.
Plans Production Recipes needs some additional rework.
=> feat(ui): ptable to replace ntable

src/features/empire/components/EmpirePlanList.vue, src/features/planning/components/PlanStatusBar.vue, src/features/planning_data/usePlan.ts
unify empire and plan status versions
=> improve(plan): unify cogc short texts
